### ISSUE TITLE
Exception with Build watch

### ISSUE THREAD

**Issue by maicol07** [jeddygong/vite-plugin-progress#10]
When watching a vite build with `vite build --watch`, I get the following error when building for the second time:
```
node:fs:1382
  handleErrorFromBinding(ctx);
  ^

Error: EEXIST: file already exists, mkdir '/home/maicol07/Projects/Trust-IT/consent-modal/node_modules/.progress'
    at Object.mkdirSync (node:fs:1382:3)
    at setCacheData (/home/maicol07/Projects/Trust-IT/consent-modal/node_modules/.pnpm/vite-plugin-progress@0.0.6_vite@4.1.4/node_modules/vite-plugin-progress/dist/index.js:61:34)
    at Object.closeBundle (/home/maicol07/Projects/Trust-IT/consent-modal/node_modules/.pnpm/vite-plugin-progress@0.0.6_vite@4.1.4/node_modules/vite-plugin-progress/dist/index.js:151:9)
    at file:///home/maicol07/Projects/Trust-IT/consent-modal/node_modules/.pnpm/rollup@3.17.3/node_modules/rollup/dist/es/shared/node-entry.js:24171:40
    at async Promise.all (index 0)
    at async PluginDriver.hookParallel (file:///home/maicol07/Projects/Trust-IT/consent-modal/node_modules/.pnpm/rollup@3.17.3/node_modules/rollup/dist/es/shared/node-entry.js:24099:9)
    at async Object.close (file:///home/maicol07/Projects/Trust-IT/consent-modal/node_modules/.pnpm/rollup@3.17.3/node_modules/rollup/dist/es/shared/node-entry.js:25396:13) {
  errno: -17,
  syscall: 'mkdir',
  code: 'PLUGIN_ERROR',
  path: '/home/maicol07/Projects/Trust-IT/consent-modal/node_modules/.progress',
  pluginCode: 'EEXIST',
  plugin: 'vite-plugin-progress',
  hook: 'closeBundle'
}

Node.js v19.7.0
```
Can you check it?
Thanks

**Comment by jeddygong** [comment]
fix：#9 
upgrade [v0.0.7](https://github.com/jeddygong/vite-plugin-progress/releases/tag/v0.0.7) @maicol07
